on:
  # 2
  push:
    branches: [ "main" ,"tilted_model"]
  pull_request:
    branches: [ "main","tilted_model" ]
 # workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest
    # runs-on: macos-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.3.9"
          channel: 'stable'
          cache: true
      # 12
      # - name: Get dependencies
        # run: flutter pub get
      # - name: Build APK
      #   run: flutter build apk --release
      #   # run: |
      #   #   flutter build ios --no-codesign
      #   #   cd build/ios/iphoneos
      #   #   mkdir Payload
      #   #   ln -S ../Runner.app
      #   #   cd ..
      #   #   zip -r app.ipa Payload

      # - name: Push to Releases
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/apk/release/*"
      #     tag: v1.0.${{github.run_number}}
      #     token: ${{secrets.HAJIRTOKEN}}
      
      # Runs a set of commands using the runners shell
      # - name: Start release build
      #   run: flutter build appbundle

      - name: Get Today Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      # - name: Get Folder id by condition
      #   uses: haya14busa/action-cond@v1
      #   id: folderId
      #   with:
      #     cond: ${{ steps.branch.outputs.branch == 'main' }}
      - run: flutter build apk
      - name: Archive Files
        run: |
          sudo apt-get install zip
          zip -r archive.zip *
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{secrets.TOKEN}}
          filename: "build/app/outputs/apk/release/app-release.apk"
          folderId: "15f5i-X7ckd1Q8BGNZ0Ch9gm3eJomidZe"
          name: TICTACTOE.v1.0.${{github.run_number}}-${{steps.date.outputs.date}}.apk #"documentation.zip" # optional string
          overwrite: "true" # optional boolean
          mimeType: "application/vnd.android.package-archive"